# CreditWise AI — Data Understanding

## Objective

Understand, profile and validate the CreditWise application dataset
before performing data cleaning, feature engineering and machine learning.

Dataset:
- 12,000 applications
- 44 columns
- 21 source columns
- 13 synthetic enrichment columns
- 10 derived columns

Target:
- approved

In [39]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print("CreditWise AI — Data Understanding")
print("Libraries loaded successfully.")

CreditWise AI — Data Understanding
Libraries loaded successfully.

In [40]:
df = pd.read_csv(
    "../data/raw/creditwise_enriched_synthetic_dataset.csv"
)

print("Dataset loaded successfully.")

Dataset loaded successfully.

In [41]:
df.head()

,applicant_id,gender,age,num_children,family_size,family_status,education_type,housing_type,own_car,own_property,income_type,occupation_type,annual_income,years_employed,credit_history_months,existing_credit_lines,debt_to_income_ratio,late_payments_24m,has_email,has_work_phone,approved,application_date,product_type,requested_credit_limit,application_channel,application_purpose,monthly_debt_obligation,monthly_expenses,total_outstanding_debt,current_credit_limit,current_credit_balance,credit_score,synthetic_enrichment,synthetic_version,monthly_income,disposable_income,credit_utilization_ratio,total_credit_exposure,income_band,dti_band,credit_history_band,employment_band,payment_risk_indicator,model_target_approval
0,100000,M,33,0,2,Married,Secondary,With parents,N,Y,Commercial associate,Laborers,71300.0,NaN,21,1,0.115,0,0,1,1,2025-02-25,Credit Card,20065.47,Mobile App,General Spending,660.14,2969.27,8274.17,36334.85,5342.38,634,1,v1.0,5941.67,2312.26,0.1470,13616.55,High,Low,Developing,Experienced,Low,1
1,100001,F,42,3,4,Married,Secondary,Rented apartment,N,Y,Working,High skill tech staff,33200.0,1.3,75,3,0.323,0,1,1,0,2026-04-28,Credit Card,53674.52,Branch,General Spending,830.36,1066.33,7063.80,35720.22,10314.27,678,1,v1.0,2766.67,869.98,0.2888,17378.07,Medium,Moderate,Long,Early Career,Low,0
2,100002,F,48,0,1,Widow,Secondary,House / apartment,N,Y,Working,Managers,67500.0,4.2,35,1,0.242,0,1,0,1,2026-02-12,Credit Card,82440.46,Partner,Education,1243.43,3076.01,29662.97,39803.79,10278.46,579,1,v1.0,5625.00,1305.56,0.2582,39941.43,High,Moderate,Developing,Experienced,Low,1
3,100003,F,31,0,1,Married,Higher education,With parents,Y,Y,Commercial associate,Laborers,42100.0,2.1,50,1,0.301,0,1,0,0,2025-10-01,Credit Card,58169.23,Mobile App,General Spending,960.28,1414.25,22678.24,19934.26,2593.58,588,1,v1.0,3508.33,1133.80,0.1301,25271.82,Medium,Moderate,Established,Early Career,Low,0
4,100004,M,48,1,3,Separated,Incomplete higher,House / apartment,N,N,Pensioner,Laborers,20000.0,NaN,167,0,0.000,0,0,0,1,2025-09-27,Credit Card,78661.13,Branch,General Spending,0.00,594.96,0.00,7355.47,1195.75,730,1,v1.0,1666.67,1071.71,0.1626,1195.75,Low,Low,Long,Experienced,Low,1

In [42]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 12000
Columns: 44

In [43]:
df.columns.tolist()

['applicant_id',
 'gender',
 'age',
 'num_children',
 'family_size',
 'family_status',
 'education_type',
 'housing_type',
 'own_car',
 'own_property',
 'income_type',
 'occupation_type',
 'annual_income',
 'years_employed',
 'credit_history_months',
 'existing_credit_lines',
 'debt_to_income_ratio',
 'late_payments_24m',
 'has_email',
 'has_work_phone',
 'approved',
 'application_date',
 'product_type',
 'requested_credit_limit',
 'application_channel',
 'application_purpose',
 'monthly_debt_obligation',
 'monthly_expenses',
 'total_outstanding_debt',
 'current_credit_limit',
 'current_credit_balance',
 'credit_score',
 'synthetic_enrichment',
 'synthetic_version',
 'monthly_income',
 'disposable_income',
 'credit_utilization_ratio',
 'total_credit_exposure',
 'income_band',
 'dti_band',
 'credit_history_band',
 'employment_band',
 'payment_risk_indicator',
 'model_target_approval']

In [44]:
for i, column in enumerate(df.columns, start=1):
    print(f"{i:02d}. {column}")

01. applicant_id
02. gender
03. age
04. num_children
05. family_size
06. family_status
07. education_type
08. housing_type
09. own_car
10. own_property
11. income_type
12. occupation_type
13. annual_income
14. years_employed
15. credit_history_months
16. existing_credit_lines
17. debt_to_income_ratio
18. late_payments_24m
19. has_email
20. has_work_phone
21. approved
22. application_date
23. product_type
24. requested_credit_limit
25. application_channel
26. application_purpose
27. monthly_debt_obligation
28. monthly_expenses
29. total_outstanding_debt
30. current_credit_limit
31. current_credit_balance
32. credit_score
33. synthetic_enrichment
34. synthetic_version
35. monthly_income
36. disposable_income
37. credit_utilization_ratio
38. total_credit_exposure
39. income_band
40. dti_band
41. credit_history_band
42. employment_band
43. payment_risk_indicator
44. model_target_approval

In [45]:
source_columns = [
    "applicant_id",
    "gender",
    "age",
    "num_children",
    "family_size",
    "family_status",
    "education_type",
    "housing_type",
    "own_car",
    "own_property",
    "income_type",
    "occupation_type",
    "annual_income",
    "years_employed",
    "credit_history_months",
    "existing_credit_lines",
    "debt_to_income_ratio",
    "late_payments_24m",
    "has_email",
    "has_work_phone",
    "approved"
]
print("Source columns:", len(source_columns))

Source columns: 21

In [46]:
synthetic_columns = [
    "application_date",
    "product_type",
    "requested_credit_limit",
    "application_channel",
    "application_purpose",
    "monthly_debt_obligation",
    "monthly_expenses",
    "total_outstanding_debt",
    "current_credit_limit",
    "current_credit_balance",
    "credit_score",
    "synthetic_enrichment",
    "synthetic_version"
]
print("Synthetic columns:", len(synthetic_columns))

Synthetic columns: 13

In [47]:
derived_columns = [
    "monthly_income",
    "disposable_income",
    "credit_utilization_ratio",
    "total_credit_exposure",
    "income_band",
    "dti_band",
    "credit_history_band",
    "employment_band",
    "payment_risk_indicator",
    "model_target_approval"
]
print("Derived columns:", len(derived_columns))

Derived columns: 10

In [48]:
print(
    len(source_columns)
    + len(synthetic_columns)
    + len(derived_columns)
)

44

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 44 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   applicant_id              12000 non-null  int64
 1   gender                    12000 non-null  object
 2   age                       12000 non-null  int64
 3   num_children              12000 non-null  int64
 4   family_size               12000 non-null  int64
 5   family_status             12000 non-null  object
 6   education_type            12000 non-null  object
 7   housing_type              12000 non-null  object
 8   own_car                   11866 non-null  object
 9   own_property              12000 non-null  object
 10  income_type               12000 non-null  object
 11  occupation_type           11266 non-null  object
 12  annual_income             12000 non-null  float64
 13  years_employed            11649 non-null  float64
 14  credit_history_months     12000 non-null  int64
 15  existing_credit_lines     12000 non-null  int64
 16  debt_to_income_ratio      12000 non-null  float64
 17  late_payments_24m         12000 non-null  int64
 18  has_email                 12000 non-null  int64
 19  has_work_phone            12000 non-null  int64
 20  approved                  12000 non-null  int64
 21  application_date          12000 non-null  object
 22  product_type              12000 non-null  object
 23  requested_credit_limit    12000 non-null  float64
 24  application_channel       12000 non-null  object
 25  application_purpose       12000 non-null  object
 26  monthly_debt_obligation   12000 non-null  float64
 27  monthly_expenses          12000 non-null  float64
 28  total_outstanding_debt    12000 non-null  float64
 29  current_credit_limit      12000 non-null  float64
 30  current_credit_balance    12000 non-null  float64
 31  credit_score              12000 non-null  int64
 32  synthetic_enrichment      12000 non-null  int64
 33  synthetic_version         12000 non-null  object
 34  monthly_income            12000 non-null  float64
 35  disposable_income         12000 non-null  float64
 36  credit_utilization_ratio  12000 non-null  float64
 37  total_credit_exposure     12000 non-null  float64
 38  income_band               12000 non-null  object
 39  dti_band                  12000 non-null  object
 40  credit_history_band       12000 non-null  object
 41  employment_band           12000 non-null  object
 42  payment_risk_indicator    12000 non-null  object
 43  model_target_approval     12000 non-null  int64
dtypes: float64(13), int64(13), object(18)
memory usage: 4.0+ MB

In [50]:
data_profile = pd.DataFrame({
    "column": df.columns,
    "data_type": df.dtypes.astype(str).values,
    "missing_count": df.isna().sum().values,
    "missing_percentage": (
        df.isna().mean() * 100
    ).round(2).values,
    "unique_values": [
        df[col].nunique(dropna=False)
        for col in df.columns
    ]
})

data_profile

,column,data_type,missing_count,missing_percentage,unique_values
0,applicant_id,int64,0,0.00,12000
1,gender,object,0,0.00,2
2,age,int64,0,0.00,50
3,num_children,int64,0,0.00,5
4,family_size,int64,0,0.00,6
5,family_status,object,0,0.00,5
6,education_type,object,0,0.00,5
7,housing_type,object,0,0.00,5
8,own_car,object,134,1.12,3
9,own_property,object,0,0.00,2
10,income_type,object,0,0.00,5
11,occupation_type,object,734,6.12,12
12,annual_income,float64,0,0.00,1344
13,years_employed,float64,351,2.92,351
14,credit_history_months,int64,0,0.00,275
15,existing_credit_lines,int64,0,0.00,8
16,debt_to_income_ratio,float64,0,0.00,525
17,late_payments_24m,int64,0,0.00,7
18,has_email,int64,0,0.00,2
19,has_work_phone,int64,0,0.00,2
20,approved,int64,0,0.00,2
21,application_date,object,0,0.00,623
22,product_type,object,0,0.00,3
23,requested_credit_limit,float64,0,0.00,11989
24,application_channel,object,0,0.00,4
25,application_purpose,object,0,0.00,5
26,monthly_debt_obligation,float64,0,0.00,11585
27,monthly_expenses,float64,0,0.00,11808
28,total_outstanding_debt,float64,0,0.00,11874
29,current_credit_limit,float64,0,0.00,11860
30,current_credit_balance,float64,0,0.00,11945
31,credit_score,int64,0,0.00,307
32,synthetic_enrichment,int64,0,0.00,1
33,synthetic_version,object,0,0.00,1
34,monthly_income,float64,0,0.00,1344
35,disposable_income,float64,0,0.00,11751
36,credit_utilization_ratio,float64,0,0.00,3520
37,total_credit_exposure,float64,0,0.00,11988
38,income_band,object,0,0.00,4
39,dti_band,object,0,0.00,4
40,credit_history_band,object,0,0.00,4
41,employment_band,object,0,0.00,4
42,payment_risk_indicator,object,0,0.00,4
43,model_target_approval,int64,0,0.00,2

In [51]:
missing_report = (
    data_profile[
        data_profile["missing_count"] > 0
    ]
    .sort_values(
        "missing_percentage",
        ascending=False
    )
)

missing_report

,column,data_type,missing_count,missing_percentage,unique_values
11,occupation_type,object,734,6.12,12
13,years_employed,float64,351,2.92,351
8,own_car,object,134,1.12,3

In [52]:
duplicate_rows = df.duplicated().sum()

print("Duplicate rows:", duplicate_rows)

Duplicate rows: 0

In [53]:
duplicate_ids = df["applicant_id"].duplicated().sum()

print("Duplicate applicant IDs:", duplicate_ids)

Duplicate applicant IDs: 0

In [54]:
df["approved"].value_counts()

approved
0    7238
1    4762
Name: count, dtype: int64

In [55]:
df["approved"].value_counts(normalize=True) * 100

approved
0    60.316667
1    39.683333
Name: proportion, dtype: float64

In [56]:
approval_summary = pd.DataFrame({
    "count": df["approved"].value_counts(),
    "percentage": (
        df["approved"]
        .value_counts(normalize=True)
        .mul(100)
        .round(2)
    )
})

approval_summary

          count  percentage
approved
0          7238       60.32
1          4762       39.68

# Step 13 — Numerical analysis

In [57]:
numeric_columns = df.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

print("Number of numerical columns:", len(numeric_columns))

numeric_columns

Number of numerical columns: 26

['applicant_id',
 'age',
 'num_children',
 'family_size',
 'annual_income',
 'years_employed',
 'credit_history_months',
 'existing_credit_lines',
 'debt_to_income_ratio',
 'late_payments_24m',
 'has_email',
 'has_work_phone',
 'approved',
 'requested_credit_limit',
 'monthly_debt_obligation',
 'monthly_expenses',
 'total_outstanding_debt',
 'current_credit_limit',
 'current_credit_balance',
 'credit_score',
 'synthetic_enrichment',
 'monthly_income',
 'disposable_income',
 'credit_utilization_ratio',
 'total_credit_exposure',
 'model_target_approval']

In [58]:
df[numeric_columns].describe().T

,count,mean,std,min,25%,50%,75%,max
applicant_id,12000.0,105999.500000,3464.245950,100000.00,102999.750000,105999.5000,108999.2500,111999.0000
age,12000.0,39.814250,10.508907,21.00,32.000000,40.0000,47.0000,70.0000
num_children,12000.0,0.766833,1.023908,0.00,0.000000,0.0000,1.0000,4.0000
family_size,12000.0,2.411833,1.128051,1.00,2.000000,2.0000,3.0000,6.0000
annual_income,12000.0,54987.883333,28553.415055,12000.00,35100.000000,49400.0000,68700.0000,255200.0000
years_employed,11649.0,5.258220,6.106028,0.00,0.800000,3.3000,7.6000,45.0000
credit_history_months,12000.0,73.243833,52.981495,0.00,33.000000,63.0000,104.0000,307.0000
existing_credit_lines,12000.0,1.404000,1.171565,0.00,1.000000,1.0000,2.0000,7.0000
debt_to_income_ratio,12000.0,0.228380,0.097501,0.00,0.162000,0.2270,0.2920,0.6150
late_payments_24m,12000.0,0.048667,0.321414,0.00,0.000000,0.0000,0.0000,6.0000
has_email,12000.0,0.657167,0.474676,0.00,0.000000,1.0000,1.0000,1.0000
has_work_phone,12000.0,0.340667,0.473953,0.00,0.000000,0.0000,1.0000,1.0000
approved,12000.0,0.396833,0.489261,0.00,0.000000,0.0000,1.0000,1.0000
requested_credit_limit,12000.0,60893.230982,32937.231492,11144.40,30555.232500,57869.3300,86017.7475,145796.7500
monthly_debt_obligation,12000.0,1048.082446,757.126564,0.00,526.452500,878.2050,1360.6875,9645.6500
monthly_expenses,12000.0,2185.380037,1257.050305,305.00,1302.295000,1913.7200,2758.4025,12098.0800
total_outstanding_debt,12000.0,16812.242798,13780.216342,0.00,7630.607500,13346.5700,21776.6125,223854.6200
current_credit_limit,12000.0,30135.363368,15949.400555,5000.00,18553.390000,27418.2500,39052.3000,120151.9800
current_credit_balance,12000.0,6856.126973,4994.998012,100.00,3280.962500,5674.3700,9169.1950,46680.2600
credit_score,12000.0,654.067167,54.520284,464.00,614.000000,654.0000,695.0000,811.0000
synthetic_enrichment,12000.0,1.000000,0.000000,1.00,1.000000,1.0000,1.0000,1.0000
monthly_income,12000.0,4582.323638,2379.451219,1000.00,2925.000000,4116.6700,5725.0000,21266.6700
disposable_income,12000.0,1348.861155,1011.980379,-2729.54,653.150000,1134.9000,1792.1825,11093.7100
credit_utilization_ratio,12000.0,0.222521,0.089516,0.02,0.161575,0.2192,0.2788,0.8544
total_credit_exposure,12000.0,23668.369771,16752.782229,223.47,12288.057500,19779.5450,30408.8575,231733.2800
model_target_approval,12000.0,0.396833,0.489261,0.00,0.000000,0.0000,1.0000,1.0000

# Step 14 — Categorical analysis

In [59]:
categorical_columns = df.select_dtypes(
    include=["object"]
).columns.tolist()

print("Number of categorical columns:", len(categorical_columns))

categorical_columns

Number of categorical columns: 18

['gender',
 'family_status',
 'education_type',
 'housing_type',
 'own_car',
 'own_property',
 'income_type',
 'occupation_type',
 'application_date',
 'product_type',
 'application_channel',
 'application_purpose',
 'synthetic_version',
 'income_band',
 'dti_band',
 'credit_history_band',
 'employment_band',
 'payment_risk_indicator']

In [60]:
for col in categorical_columns:
    print(f"\n{'='*50}")
    print(col)
    print("="*50)
    print(df[col].value_counts(dropna=False).head(20))

==================================================
gender
==================================================
gender
F    6179
M    5821
Name: count, dtype: int64

==================================================
family_status
==================================================
family_status
Married                 6977
Single / not married    2402
Separated               1086
Civil marriage          1004
Widow                    531
Name: count, dtype: int64

==================================================
education_type
==================================================
education_type
Secondary            5372
Higher education     3849
Incomplete higher    1482
Lower secondary       807
Academic degree       490
Name: count, dtype: int64

==================================================
housing_type
==================================================
housing_type
House / apartment      7725
Rented apartment       1649
With parents           1431
Municipal apartment     849
Co-op apartment         346
Name: count, dtype: int64

==================================================
own_car
==================================================
own_car
N      7060
Y      4806
NaN     134
Name: count, dtype: int64

==================================================
own_property
==================================================
own_property
Y    7439
N    4561
Name: count, dtype: int64

==================================================
income_type
==================================================
income_type
Working                 6259
Commercial associate    2615
Pensioner               1810
State servant           1093
Student                  223
Name: count, dtype: int64

==================================================
occupation_type
==================================================
occupation_type
Laborers                 2271
Sales staff              1573
Core staff               1501
Managers                 1224
Drivers                  1028
High skill tech staff     873
Accountants               743
NaN                       734
Medicine staff            666
Security staff            593
Cooking staff             429
Unemployed                365
Name: count, dtype: int64

==================================================
application_date
==================================================
application_date
2026-04-10    32
2025-03-21    31
2025-06-02    31
2026-07-02    31
2025-11-12    30
2025-09-28    30
2025-03-19    30
2026-08-21    29
2026-08-07    29
2025-07-31    29
2025-10-19    29
2026-06-14    29
2026-01-26    29
2025-12-11    28
2026-05-13    28
2025-04-06    28
2026-09-10    28
2025-07-20    28
2026-01-20    28
2025-08-03    28
Name: count, dtype: int64

==================================================
product_type
==================================================
product_type
Credit Card      7759
Personal Loan    3028
Credit Line      1213
Name: count, dtype: int64

==================================================
application_channel
==================================================
application_channel
Mobile App    4730
Web           3592
Branch        2504
Partner       1174
Name: count, dtype: int64

==================================================
application_purpose
==================================================
application_purpose
General Spending      5320
Debt Consolidation    2425
Emergency Expense     1857
Education             1214
Travel                1184
Name: count, dtype: int64

==================================================
synthetic_version
==================================================
synthetic_version
v1.0    12000
Name: count, dtype: int64

==================================================
income_band
==================================================
income_band
Medium       5778
High         3327
Low          2050
Very High     845
Name: count, dtype: int64

==================================================
dti_band
==================================================
dti_band
Moderate     5955
Low          4736
High         1265
Very High      44
Name: count, dtype: int64

==================================================
credit_history_band
==================================================
credit_history_band
Long           6227
Established    2415
Developing     2227
New            1131
Name: count, dtype: int64

==================================================
employment_band
==================================================
employment_band
New             3324
Experienced     3264
Long Tenure     3180
Early Career    2232
Name: count, dtype: int64

==================================================
payment_risk_indicator
==================================================
payment_risk_indicator
Low          11638
Moderate       220
High           122
Very High       20
Name: count, dtype: int64

# Step 15 — Binary validation

In [61]:
binary_columns = [
    "own_car",
    "own_property",
    "has_email",
    "has_work_phone",
    "approved"
]

for col in binary_columns:
    print(f"\n{col}")
    print(df[col].value_counts(dropna=False))

own_car
own_car
N      7060
Y      4806
NaN     134
Name: count, dtype: int64

own_property
own_property
Y    7439
N    4561
Name: count, dtype: int64

has_email
has_email
1    7886
0    4114
Name: count, dtype: int64

has_work_phone
has_work_phone
0    7912
1    4088
Name: count, dtype: int64

approved
approved
0    7238
1    4762
Name: count, dtype: int64

# Step 16 — Business sanity checks

In [62]:
print(
    "Age range:",
    df["age"].min(),
    "to",
    df["age"].max()
)

print(
    "DTI range:",
    df["debt_to_income_ratio"].min(),
    "to",
    df["debt_to_income_ratio"].max()
)

print(
    "DTI range:",
    df["debt_to_income_ratio"].min(),
    "to",
    df["debt_to_income_ratio"].max()
)

print(
    "Credit score range:",
    df["credit_score"].min(),
    "to",
    df["credit_score"].max()
)

print(
    "Credit utilization range:",
    df["credit_utilization_ratio"].min(),
    "to",
    df["credit_utilization_ratio"].max()
)

Age range: 21 to 70
DTI range: 0.0 to 0.615
DTI range: 0.0 to 0.615
Credit score range: 464 to 811
Credit utilization range: 0.02 to 0.8544

# Step 17 — Save the data profile

In [66]:
data_profile.to_csv(
    "../data/processed/data_profile_v1.csv",
    index=False
)

print("Data profile saved.")

Data profile saved.

In [67]:
df["own_car"].value_counts(dropna=False)

own_car
N      7060
Y      4806
NaN     134
Name: count, dtype: int64

In [74]:
df["own_car"].value_counts(dropna=False)

own_car
N      7060
Y      4806
NaN     134
Name: count, dtype: int64

In [70]:
df["occupation_type"].value_counts(dropna=False)

occupation_type
Laborers                 2271
Sales staff              1573
Core staff               1501
Managers                 1224
Drivers                  1028
High skill tech staff     873
Accountants               743
NaN                       734
Medicine staff            666
Security staff            593
Cooking staff             429
Unemployed                365
Name: count, dtype: int64

In [71]:
df["approved"].value_counts(normalize=True).mul(100).round(2)

approved
0    60.32
1    39.68
Name: proportion, dtype: float64

In [75]:
pd.to_datetime(df["application_date"]).agg(["min", "max"])

min   2025-01-01
max   2026-09-15
Name: application_date, dtype: datetime64[ns]

In [76]:
missing_by_approval = pd.DataFrame({
    "missing_occupation": df["occupation_type"].isna(),
    "missing_employment": df["years_employed"].isna(),
    "missing_car": df["own_car"].isna(),
    "approved": df["approved"]
})

missing_by_approval.groupby("approved").mean() * 100

          missing_occupation  missing_employment  missing_car
approved
0                   6.051395            2.970434     1.050014
1                   6.215876            2.855943     1.217976